# Generated by Django 5.0.8 on 2024-08-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is the task active"),
        ),
    ]
